### ISSUE TITLE
Server-Antwort: Study 4000 does not exist

### ISSUE THREAD

**Issue by bergwiesel** [KL-Psychological-Methodology/ESMira-web#1] opened 2023-04-03 10:10 UTC
Since a few days ago users get an error "Study 4000 does not exist", when they want to edit a study. I can't see anything in the logs. As an admin user I don't see this error at all.

ESMira version: 2.2.2

**Comment by JodliDev** [comment] 2023-04-03 11:01
Hm please tell me if I am mistaken, but I have a theory:

Did you, by any chance, recently delete a study (which probably had the id 4000)? And the accounts that have problems now had access to this study?
Prompted from your issue, I had a look in the backend and realised that the permissions are not cleaned up properly when deleting a study.

So - if I am correct - then the study itself has been deleted, but its permission is still there (leading to a "not found" error when an account with faulty permissions tries to load all the studies they have access to).

I think you should be able to repair the problem in the account permissions ("Change accounts" at the admin starting screen).
The accounts that cant log in, should have a permission entry that says "unknown". If you delete that, everything should be working smoothly again.

I am about to release version 2.2.3 so I will add a fix for this problem as well.

**Comment by JodliDev** [comment] 2023-04-10 11:46
Non admin users should not be able to delete a study.

Maybe the broken permission was caused by something else. Looking closer at the source, cleanup for deleted studies seems to work fine actually... So I am still unsure what could have caused it.

Ill close this for now but if it happens again please let me know.

**Closed by JodliDev** 2023-04-10 11:46 UTC
